### ISSUE TITLE
The current version

### ISSUE THREAD

**Issue by traumschule** [fnordomat/oniongitshare#1]
can be found at https://notabug.org/themusicgod1/cloudflare-tor/src/master/globalist

**Comment by fnordomat** [comment]
Interesting. I wasn't even aware of that.

**Comment by fnordomat** [comment]
The link is dead, what happened to it?

**Comment by fnordomat** [comment]
The current version is now at https://notabug.org/fnordomat/oniongitshare. *
Please note the issue tracker there.
Once it works as intended, it will become self-hosting.
